PORT_AUSER = 9050
PORT_AUPDATER = 9051
PORT_ASENDER = 9052
PORT_APURCHASES = 9053
PORT_AADMIN = 9054
PORT_SENDER_DIRECTORY = 9055
PORT_SEHOOR_SENDER = 9100
PORT_OOPS_SENDER = 9101

OUR_SELLING_COMPANY_NAME = 'ECSDIMAZON'

NAMESPACE = 'http://www.owl-ontologies.com/Ontology1463560793.owl'

PAYMENT_PAYPAL = 'paypal'
PAYMENT_VISA = 'visa'

PRIORITY_LOW = 'low'
PRIORITY_MEDIUM = 'medium'
PRIORITY_HIGH = 'high'

REASON_DEFECTIVE = "1. Producto defectuoso."
REASON_WRONG_PRODUCT = "2. Producto equivocado."
REASON_NON_SATISFACTORY = "3. No me satisface (solo aplica los primeros 15 dias)"
REASON_DICT = {
    1: REASON_DEFECTIVE,
    2: REASON_WRONG_PRODUCT,
    3: REASON_NON_SATISFACTORY
}
