PORT_AUSER = 9050
PORT_AUPDATER = 9051
PORT_ASENDER = 9052
PORT_APURCHASES = 9053
PORT_AADMIN = 9054
PORT_SENDER_DIRECTORY = 9055

OUR_SELLING_COMPANY_NAME = 'ECSDIMAZON'

NAMESPACE = 'http://www.owl-ontologies.com/Ontology1463560793.owl'

PAYMENT_PAYPAL = 'paypal'
PAYMENT_VISA = 'visa'

PRIORITY_LOW = 'low'
PRIORITY_MEDIUM = 'medium'
PRIORITY_HIGH = 'high'
